spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: H!IIk3*hJYCd
    driver-class-name: com.mysql.cj.jdbc.Driver
